### ISSUE TITLE
Improve zuul-jobs role integration

### ISSUE THREAD

**Issue by TristanCacqueray** [logreduce/logreduce#60]
Using the `run-logreduce` in zuul jobs presently requires adding the role to be base job post action, between the `fetch-output` and `upload-logs` roles. To simplify the usage:

- [x] Add a one-task role `logreduce-report` to create an artifact link the web api. This role could be used anywhere by a job, e.g. in untrusted play phase.
```yaml
  - include_role:
      name: logreduce-report
      # the logreduce api
      logreduce_url: https://softwarefactory-project.io/logreduce
      # the zuul api (zuul job don't know the public url)
      zuul_url: https://softwarefactory-project.io/zuul 
    when: not zuul.success
```

- [x] Enable using `run-logreduce` on the test node in the untrusted play phase. To achieve this, the following heuristic needs to be implemented:
  - [x] When `ansible_play_hosts_all` contains a single host, copy the job_output.txt from the executor to the host and run logreduce as usual.
  - [x] The role would skip the process when `ansible_play_hosts_all` contains multiple host. This requires tricky work, e.g. to process the job_output.txt on the first host (when ansible_host is the first item) and merge the report after the fetch-output. That could be done in a follow-up when necessary.
